# Generated by Django 6.0.1 on 2026-01-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('vin_no', models.CharField(max_length=100)),
                ('front_tire', models.CharField(choices=[('excellent', 'Excellent'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('rear_tire', models.CharField(choices=[('excellent', 'Excellent'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('front_pads', models.CharField(choices=[('excellent', 'Excellent'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('rear_pads', models.CharField(choices=[('excellent', 'Excellent'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('battery_voltage', models.CharField(choices=[('excellent', 'Excellent'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('charging_output', models.CharField(choices=[('excellent', 'Excellent'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
