# Generated by Django 6.0.1 on 2026-01-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='remarks',
            new_name='customer_signature',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='battery_voltage',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='charging_output',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='front_pads',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='front_tire',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='rear_pads',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='rear_tire',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='end_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sales_order_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='start_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='vin_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('medium', 'Medium'), ('bad', 'Bad')], max_length=20)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='jobcard.jobcard')),
            ],
        ),
    ]
