# Generated by Django 6.0.1 on 2026-01-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0002_rename_remarks_jobcard_customer_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_signature',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='end_km',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='quotation_no',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='sales_order_no',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='start_km',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vin_no',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='inspection',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='invoice',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='qc',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='quotation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='receive_deliver',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='requests',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sales',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vin',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InspectionItem',
        ),
    ]
