# Generated by Django 6.0.1 on 2026-01-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0003_remove_jobcard_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
