# Generated by Django 6.0.1 on 2026-01-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0005_jobcard_status_jobcard_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='invoice',
            field=models.CharField(default='', max_length=50),
        ),
    ]
