# Generated by Django 6.0.5 on 2026-05-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0006_alter_jobcard_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='customer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='inspection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='invoice',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='qc',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='receive_deliver',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='requests',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
