# Generated by Django 6.0.5 on 2026-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0007_alter_jobcard_customer_alter_jobcard_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='jobcards/'),
        ),
    ]
